name: Hologram
version: 1.0
description: Hologram Plugin made by Yujun Oh
main : kr.ohurjon.plugin.hologram.HologramPlugin
authors:
  - ohurjon
website: ohurjon.kro.kr

load: POSTWORLD

depend :
  - kotlin-stdlib
loadbefore :
  - kotlin-stdlib

commands:
  hologram:
    description: "hologram command"